language: node_js
node_js:
- node
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh-keyscan -p $PROD_PORT $PROD_SERVER 2>&1 >> $HOME/.ssh/known_hosts
deploy:
  provider: script
  cleanup: false
  script: npm run build && rsync -e "ssh -p $PROD_PORT" -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist $PROD_USER@$PROD_SERVER:$PROD_DIR
  on:
    branch: master
