language: node_js
node_js:
- node
addons:
  ssh_known_hosts:
  - $PROD_SERVER
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -e "ssh -p $PROD_PORT" -r --delete-after --quiet $TRAVIS_BUILD_DIR/build $PROD_USER@$PROD_SERVER:$PROD_DIR
  on:
    branch: master
