language: node_js
node_js:
    - node
env:
    - BRANCH=$([ "$TRAVIS_PULL_REQUEST" = "false" ] && echo "$TRAVIS_BRANCH" || echo "$TRAVIS_PULL_REQUEST_BRANCH")
before_install:
    - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    - ssh-keyscan -p $PROD_PORT $PROD_SERVER 2>&1 >> $HOME/.ssh/known_hosts
#script: yarn run $RUN_SCRIPT
script: yarn run predev
after_success:
#     neuer branch dann merge in BRANCH
    - git checkout -b temp
    - git remote
    - git config user.email developer@lss-manager.de
    - git config user.name LSS-Manager-Bot
    - git add --all
    - git commit -m "👷 [BUILD] $TRAVIS_BUILD_NUMBER"
    - git merge $BRANCH
    - git push "https://${GH_TOKEN}@github.com/LSS-Manager/LSSM-V.4.git" $BRANCH
deploy:
    provider: script
    skip_cleanup: true
    script: rsync -e "ssh -p $PROD_PORT" -r --delete-after $TRAVIS_BUILD_DIR/dist/ $PROD_USER@$PROD_SERVER:$DIR
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^(master|dev)$
