version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "KBOE2"
    commit-message:
        prefix: "⬆️"
        include: "scope"
    reviewers:
      - "KBOE2"
